/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: agent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "agent.pb-c.h"
void   jaegertracing__protobuf__agent__empty__init
                     (Jaegertracing__Protobuf__Agent__Empty         *message)
{
  static const Jaegertracing__Protobuf__Agent__Empty init_value = JAEGERTRACING__PROTOBUF__AGENT__EMPTY__INIT;
  *message = init_value;
}
size_t jaegertracing__protobuf__agent__empty__get_packed_size
                     (const Jaegertracing__Protobuf__Agent__Empty *message)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__agent__empty__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t jaegertracing__protobuf__agent__empty__pack
                     (const Jaegertracing__Protobuf__Agent__Empty *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__agent__empty__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t jaegertracing__protobuf__agent__empty__pack_to_buffer
                     (const Jaegertracing__Protobuf__Agent__Empty *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__agent__empty__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Jaegertracing__Protobuf__Agent__Empty *
       jaegertracing__protobuf__agent__empty__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Jaegertracing__Protobuf__Agent__Empty *)
     protobuf_c_message_unpack (&jaegertracing__protobuf__agent__empty__descriptor,
                                allocator, len, data);
}
void   jaegertracing__protobuf__agent__empty__free_unpacked
                     (Jaegertracing__Protobuf__Agent__Empty *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &jaegertracing__protobuf__agent__empty__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define jaegertracing__protobuf__agent__empty__field_descriptors NULL
#define jaegertracing__protobuf__agent__empty__field_indices_by_name NULL
#define jaegertracing__protobuf__agent__empty__number_ranges NULL
const ProtobufCMessageDescriptor jaegertracing__protobuf__agent__empty__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.agent.Empty",
  "Empty",
  "Jaegertracing__Protobuf__Agent__Empty",
  "jaegertracing.protobuf.agent",
  sizeof(Jaegertracing__Protobuf__Agent__Empty),
  0,
  jaegertracing__protobuf__agent__empty__field_descriptors,
  jaegertracing__protobuf__agent__empty__field_indices_by_name,
  0,  jaegertracing__protobuf__agent__empty__number_ranges,
  (ProtobufCMessageInit) jaegertracing__protobuf__agent__empty__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor jaegertracing__protobuf__agent__agent__method_descriptors[1] =
{
  { "EmitBatch", &jaegertracing__protobuf__batch__descriptor, &jaegertracing__protobuf__agent__empty__descriptor },
};
const unsigned jaegertracing__protobuf__agent__agent__method_indices_by_name[] = {
  0         /* EmitBatch */
};
const ProtobufCServiceDescriptor jaegertracing__protobuf__agent__agent__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.agent.Agent",
  "Agent",
  "Jaegertracing__Protobuf__Agent__Agent",
  "jaegertracing.protobuf.agent",
  1,
  jaegertracing__protobuf__agent__agent__method_descriptors,
  jaegertracing__protobuf__agent__agent__method_indices_by_name
};
void jaegertracing__protobuf__agent__agent__emit_batch(ProtobufCService *service,
                                                       const Jaegertracing__Protobuf__Batch *input,
                                                       Jaegertracing__Protobuf__Agent__Empty_Closure closure,
                                                       void *closure_data)
{
  assert(service->descriptor == &jaegertracing__protobuf__agent__agent__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void jaegertracing__protobuf__agent__agent__init (Jaegertracing__Protobuf__Agent__Agent_Service *service,
                                                  Jaegertracing__Protobuf__Agent__Agent_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &jaegertracing__protobuf__agent__agent__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
