/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sampling.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sampling.pb-c.h"
void   jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__init
                     (Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy         *message)
{
  static const Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy init_value = JAEGERTRACING__PROTOBUF__SAMPLING_MANAGER__PROBABILISTIC_SAMPLING_STRATEGY__INIT;
  *message = init_value;
}
size_t jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__get_packed_size
                     (const Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy *message)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__pack
                     (const Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__pack_to_buffer
                     (const Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy *
       jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy *)
     protobuf_c_message_unpack (&jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__descriptor,
                                allocator, len, data);
}
void   jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__free_unpacked
                     (Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__init
                     (Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy         *message)
{
  static const Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy init_value = JAEGERTRACING__PROTOBUF__SAMPLING_MANAGER__RATE_LIMITING_SAMPLING_STRATEGY__INIT;
  *message = init_value;
}
size_t jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__get_packed_size
                     (const Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy *message)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__pack
                     (const Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__pack_to_buffer
                     (const Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy *
       jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy *)
     protobuf_c_message_unpack (&jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__descriptor,
                                allocator, len, data);
}
void   jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__free_unpacked
                     (Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__init
                     (Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy         *message)
{
  static const Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy init_value = JAEGERTRACING__PROTOBUF__SAMPLING_MANAGER__PER_OPERATION_SAMPLING_STRATEGY__OPERATION_SAMPLING_STRATEGY__INIT;
  *message = init_value;
}
void   jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__init
                     (Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy         *message)
{
  static const Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy init_value = JAEGERTRACING__PROTOBUF__SAMPLING_MANAGER__PER_OPERATION_SAMPLING_STRATEGY__INIT;
  *message = init_value;
}
size_t jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__get_packed_size
                     (const Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy *message)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__pack
                     (const Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__pack_to_buffer
                     (const Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy *
       jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy *)
     protobuf_c_message_unpack (&jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__descriptor,
                                allocator, len, data);
}
void   jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__free_unpacked
                     (Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   jaegertracing__protobuf__sampling_manager__sampling_strategy_request__init
                     (Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest         *message)
{
  static const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest init_value = JAEGERTRACING__PROTOBUF__SAMPLING_MANAGER__SAMPLING_STRATEGY_REQUEST__INIT;
  *message = init_value;
}
size_t jaegertracing__protobuf__sampling_manager__sampling_strategy_request__get_packed_size
                     (const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest *message)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__sampling_strategy_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t jaegertracing__protobuf__sampling_manager__sampling_strategy_request__pack
                     (const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__sampling_strategy_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t jaegertracing__protobuf__sampling_manager__sampling_strategy_request__pack_to_buffer
                     (const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__sampling_strategy_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest *
       jaegertracing__protobuf__sampling_manager__sampling_strategy_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest *)
     protobuf_c_message_unpack (&jaegertracing__protobuf__sampling_manager__sampling_strategy_request__descriptor,
                                allocator, len, data);
}
void   jaegertracing__protobuf__sampling_manager__sampling_strategy_request__free_unpacked
                     (Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__sampling_strategy_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   jaegertracing__protobuf__sampling_manager__sampling_strategy_response__init
                     (Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse         *message)
{
  static const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse init_value = JAEGERTRACING__PROTOBUF__SAMPLING_MANAGER__SAMPLING_STRATEGY_RESPONSE__INIT;
  *message = init_value;
}
size_t jaegertracing__protobuf__sampling_manager__sampling_strategy_response__get_packed_size
                     (const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse *message)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__sampling_strategy_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t jaegertracing__protobuf__sampling_manager__sampling_strategy_response__pack
                     (const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__sampling_strategy_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t jaegertracing__protobuf__sampling_manager__sampling_strategy_response__pack_to_buffer
                     (const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__sampling_strategy_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse *
       jaegertracing__protobuf__sampling_manager__sampling_strategy_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse *)
     protobuf_c_message_unpack (&jaegertracing__protobuf__sampling_manager__sampling_strategy_response__descriptor,
                                allocator, len, data);
}
void   jaegertracing__protobuf__sampling_manager__sampling_strategy_response__free_unpacked
                     (Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &jaegertracing__protobuf__sampling_manager__sampling_strategy_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__field_descriptors[1] =
{
  {
    "sampling_rate",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy, sampling_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__field_indices_by_name[] = {
  0,   /* field[0] = sampling_rate */
};
static const ProtobufCIntRange jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.sampling_manager.ProbabilisticSamplingStrategy",
  "ProbabilisticSamplingStrategy",
  "Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy",
  "jaegertracing.protobuf.sampling_manager",
  sizeof(Jaegertracing__Protobuf__SamplingManager__ProbabilisticSamplingStrategy),
  1,
  jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__field_descriptors,
  jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__field_indices_by_name,
  1,  jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__number_ranges,
  (ProtobufCMessageInit) jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__field_descriptors[1] =
{
  {
    "max_traces_per_seconds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy, max_traces_per_seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__field_indices_by_name[] = {
  0,   /* field[0] = max_traces_per_seconds */
};
static const ProtobufCIntRange jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.sampling_manager.RateLimitingSamplingStrategy",
  "RateLimitingSamplingStrategy",
  "Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy",
  "jaegertracing.protobuf.sampling_manager",
  sizeof(Jaegertracing__Protobuf__SamplingManager__RateLimitingSamplingStrategy),
  1,
  jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__field_descriptors,
  jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__field_indices_by_name,
  1,  jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__number_ranges,
  (ProtobufCMessageInit) jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__field_descriptors[3] =
{
  {
    "operation",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy, operation),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "probabilistic",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy, strategy_case),
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy, probabilistic),
    &jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate_limiting",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy, strategy_case),
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy, rate_limiting),
    &jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__field_indices_by_name[] = {
  0,   /* field[0] = operation */
  1,   /* field[1] = probabilistic */
  2,   /* field[2] = rate_limiting */
};
static const ProtobufCIntRange jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.sampling_manager.PerOperationSamplingStrategy.OperationSamplingStrategy",
  "OperationSamplingStrategy",
  "Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy",
  "jaegertracing.protobuf.sampling_manager",
  sizeof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy__OperationSamplingStrategy),
  3,
  jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__field_descriptors,
  jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__field_indices_by_name,
  1,  jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__number_ranges,
  (ProtobufCMessageInit) jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__field_descriptors[4] =
{
  {
    "default_sampling_probability",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy, default_sampling_probability),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_lower_bound_traces_per_second",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy, default_lower_bound_traces_per_second),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_upper_bound_traces_per_second",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy, default_upper_bound_traces_per_second),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "per_operation_strategy",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy, n_per_operation_strategy),
    offsetof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy, per_operation_strategy),
    &jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__operation_sampling_strategy__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__field_indices_by_name[] = {
  1,   /* field[1] = default_lower_bound_traces_per_second */
  0,   /* field[0] = default_sampling_probability */
  2,   /* field[2] = default_upper_bound_traces_per_second */
  3,   /* field[3] = per_operation_strategy */
};
static const ProtobufCIntRange jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.sampling_manager.PerOperationSamplingStrategy",
  "PerOperationSamplingStrategy",
  "Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy",
  "jaegertracing.protobuf.sampling_manager",
  sizeof(Jaegertracing__Protobuf__SamplingManager__PerOperationSamplingStrategy),
  4,
  jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__field_descriptors,
  jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__field_indices_by_name,
  1,  jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__number_ranges,
  (ProtobufCMessageInit) jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor jaegertracing__protobuf__sampling_manager__sampling_strategy_request__field_descriptors[1] =
{
  {
    "service_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest, service_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned jaegertracing__protobuf__sampling_manager__sampling_strategy_request__field_indices_by_name[] = {
  0,   /* field[0] = service_name */
};
static const ProtobufCIntRange jaegertracing__protobuf__sampling_manager__sampling_strategy_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor jaegertracing__protobuf__sampling_manager__sampling_strategy_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.sampling_manager.SamplingStrategyRequest",
  "SamplingStrategyRequest",
  "Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest",
  "jaegertracing.protobuf.sampling_manager",
  sizeof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest),
  1,
  jaegertracing__protobuf__sampling_manager__sampling_strategy_request__field_descriptors,
  jaegertracing__protobuf__sampling_manager__sampling_strategy_request__field_indices_by_name,
  1,  jaegertracing__protobuf__sampling_manager__sampling_strategy_request__number_ranges,
  (ProtobufCMessageInit) jaegertracing__protobuf__sampling_manager__sampling_strategy_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor jaegertracing__protobuf__sampling_manager__sampling_strategy_response__field_descriptors[3] =
{
  {
    "probabilistic",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse, strategy_case),
    offsetof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse, probabilistic),
    &jaegertracing__protobuf__sampling_manager__probabilistic_sampling_strategy__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate_limiting",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse, strategy_case),
    offsetof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse, rate_limiting),
    &jaegertracing__protobuf__sampling_manager__rate_limiting_sampling_strategy__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "per_operation",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse, strategy_case),
    offsetof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse, per_operation),
    &jaegertracing__protobuf__sampling_manager__per_operation_sampling_strategy__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned jaegertracing__protobuf__sampling_manager__sampling_strategy_response__field_indices_by_name[] = {
  2,   /* field[2] = per_operation */
  0,   /* field[0] = probabilistic */
  1,   /* field[1] = rate_limiting */
};
static const ProtobufCIntRange jaegertracing__protobuf__sampling_manager__sampling_strategy_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor jaegertracing__protobuf__sampling_manager__sampling_strategy_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.sampling_manager.SamplingStrategyResponse",
  "SamplingStrategyResponse",
  "Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse",
  "jaegertracing.protobuf.sampling_manager",
  sizeof(Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse),
  3,
  jaegertracing__protobuf__sampling_manager__sampling_strategy_response__field_descriptors,
  jaegertracing__protobuf__sampling_manager__sampling_strategy_response__field_indices_by_name,
  1,  jaegertracing__protobuf__sampling_manager__sampling_strategy_response__number_ranges,
  (ProtobufCMessageInit) jaegertracing__protobuf__sampling_manager__sampling_strategy_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor jaegertracing__protobuf__sampling_manager__sampling_manager__method_descriptors[1] =
{
  { "GetSamplingStrategy", &jaegertracing__protobuf__sampling_manager__sampling_strategy_request__descriptor, &jaegertracing__protobuf__sampling_manager__sampling_strategy_response__descriptor },
};
const unsigned jaegertracing__protobuf__sampling_manager__sampling_manager__method_indices_by_name[] = {
  0         /* GetSamplingStrategy */
};
const ProtobufCServiceDescriptor jaegertracing__protobuf__sampling_manager__sampling_manager__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "jaegertracing.protobuf.sampling_manager.SamplingManager",
  "SamplingManager",
  "Jaegertracing__Protobuf__SamplingManager__SamplingManager",
  "jaegertracing.protobuf.sampling_manager",
  1,
  jaegertracing__protobuf__sampling_manager__sampling_manager__method_descriptors,
  jaegertracing__protobuf__sampling_manager__sampling_manager__method_indices_by_name
};
void jaegertracing__protobuf__sampling_manager__sampling_manager__get_sampling_strategy(ProtobufCService *service,
                                                                                        const Jaegertracing__Protobuf__SamplingManager__SamplingStrategyRequest *input,
                                                                                        Jaegertracing__Protobuf__SamplingManager__SamplingStrategyResponse_Closure closure,
                                                                                        void *closure_data)
{
  assert(service->descriptor == &jaegertracing__protobuf__sampling_manager__sampling_manager__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void jaegertracing__protobuf__sampling_manager__sampling_manager__init (Jaegertracing__Protobuf__SamplingManager__SamplingManager_Service *service,
                                                                        Jaegertracing__Protobuf__SamplingManager__SamplingManager_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &jaegertracing__protobuf__sampling_manager__sampling_manager__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
